const get=(req,res)=>{
    res.send([
        {
            "id": 1,
            "name": "Apple iPhone 14 Pro Max (128 GB)",
            "category": "Mobile",
            "image": "https://m.media-amazon.com/images/I/71yzJoE7WlL._SX342_.jpg",
            "price": 127999,
          },
          {
            "id": 2,
            "name": "Apple iPhone 14 (512 GB) ",
            "category": "Mobile",
            "image": "https://m.media-amazon.com/images/I/61bK6PMOC3L._SX342_.jpg",
            "price": 101999,
          },
          {
            "id": 3,
            "name": "Apple AirPods (2nd Generation)",
            "category": "Earpods",
            "image": "https://m.media-amazon.com/images/I/7120GgUKj3L._SX522_.jpg",
            "price": 10999,  
          },
          {
            "id": 4,
            "name": "Apple AirPods (3rd Generation)",
            "category": "Earpod",
            "image": "https://m.media-amazon.com/images/I/615ekapl+pL._SY355_.jpg",
            "price": 18999,
          },
          {
            "id": 5,
            "name": "Apple 2022 12.9-inch iPad Pro (Wi-Fi, 128GB) - Space Grey (6th Generation)",
            "category": "Ipad",
            "image": "https://m.media-amazon.com/images/I/81c+9BOQNWL._SX522_.jpg",
            "price": 111900,
          },
          {
            "id": 6,
            "name": "Lenovo Tab M10 FHD Plus (3rd Gen)",
            "category": "Ipad",
            "image": "https://m.media-amazon.com/images/I/41Qi4q8cL+L._SY300_SX300_.jpg",
            "price": 21960,
          },
          {
            "id": 7,
            "name": "Apple Watch Series 8",
            "category": "Ipad",
            "image": "https://m.media-amazon.com/images/I/71OylAZAe2L._SX522_.jpg",
            "price": 49900,
          },
          {
            "id": 8,
            "name": "ASUS Vivobook 16X",
            "category": "Laptop",
            "image": "https://m.media-amazon.com/images/I/71KEZ4zqOJL._SY355_.jpg",
            "price": 47960,
          },
          {
            "id": 9,
            "name": "OnePlus 11R 5G ",
            "category": "Ipad",
            "image": "https://m.media-amazon.com/images/I/41g1pQr8xUL._SX300_SY300_QL70_FMwebp_.jpg",
            "price": 40999,
            },
          {
            "id": 10,
            "name": "Asus TUF Gaming A17",
            "category": "Laptop",
            "image": "https://m.media-amazon.com/images/I/41N6hC-kIaL._SY300_SX300_QL70_FMwebp_.jpg",
            "price": 73500, 
          },
          {
            "id": 11,
            "name": "ASUS ROG Strix G15",
            "category": "Laptop",
            "image": "https://m.media-amazon.com/images/I/71d1w3ivZ9L._SY450_.jpg",
            "price": 76990,
          },
          {
            "id": 12,
            "name": "Fossil Nate Chronograph",
            "category": "watch",
            "image": "https://m.media-amazon.com/images/I/61fy+u9uqPL._SX679_.jpg",
            "price": 22000,
          },
          {
            "id": 13,
            "name": "OnePlus 10 Pro",
            "category": "Mobile",
            "image": "https://m.media-amazon.com/images/I/61mIUCd-37L._SL1500_.jpg",
            "price": 19500,
          
          },
          {
            "id": 14,
            "name": "OnePlus 10 R",
            "category": "Mobile",
            "image": "https://m.media-amazon.com/images/I/716uVx3Wr5L._AC_SS450_.jpg",
            "price": 35000,
          },
          {
            "id": 15,
            "name": "OnePlus Nord 2T",
            "category": "Mobile",
            "image": "https://m.media-amazon.com/images/I/617MPEZB5mL._SL1500_.jpg",
            "price": 16500,
          },
            {
              "id": 16,
              "name": "Apple iPhone 14 Pro Max (128 GB)",
              "category": "Mobile",
              "image": "https://m.media-amazon.com/images/I/71yzJoE7WlL._SX342_.jpg",
              "price": 127999,
            },
            {
              "id": 17,
              "name": "Apple iPhone 14 (512 GB) ",
              "category": "Mobile",
              "image": "https://m.media-amazon.com/images/I/61bK6PMOC3L._SX342_.jpg",
              "price": 101999,
            },
            {
              "id": 18,
              "name": "Apple AirPods (2nd Generation)",
              "category": "Earpods",
              "image": "https://m.media-amazon.com/images/I/7120GgUKj3L._SX522_.jpg",
              "price": 10999,  
            },
            {
              "id": 19,
              "name": "Apple AirPods (3rd Generation)",
              "category": "Earpod",
              "image": "https://m.media-amazon.com/images/I/615ekapl+pL._SY355_.jpg",
              "price": 18999,
            },
            {
              "id": 20,
              "name": "Apple 2022 12.9-inch iPad Pro (Wi-Fi, 128GB) - Space Grey (6th Generation)",
              "category": "Ipad",
              "image": "https://m.media-amazon.com/images/I/81c+9BOQNWL._SX522_.jpg",
              "price": 111900,
            },
            {
              "id": 21,
              "name": "Lenovo Tab M10 FHD Plus (3rd Gen)",
              "category": "Ipad",
              "image": "https://m.media-amazon.com/images/I/41Qi4q8cL+L._SY300_SX300_.jpg",
              "price": 21960,
            },
            {
              "id": 22,
              "name": "Apple Watch Series 8",
              "category": "Ipad",
              "image": "https://m.media-amazon.com/images/I/71OylAZAe2L._SX522_.jpg",
              "price": 49900,
            },
            {
              "id": 23,
              "name": "ASUS Vivobook 16X",
              "category": "Laptop",
              "image": "https://m.media-amazon.com/images/I/71KEZ4zqOJL._SY355_.jpg",
              "price": 47960,
            },
            {
              "id": 24,
              "name": "Asus TUF Gaming A17",
              "category": "Laptop",
              "image": "https://m.media-amazon.com/images/I/41N6hC-kIaL._SY300_SX300_QL70_FMwebp_.jpg",
              "price": 73500, 
            },
            {
              "id": 25,
              "name": "ASUS ROG Strix G15",
              "category": "Laptop",
              "image": "https://m.media-amazon.com/images/I/71d1w3ivZ9L._SY450_.jpg",
              "price": 76990,
            },
            {
              "id": 26,
              "name": "Fossil Nate Chronograph",
              "category": "watch",
              "image": "https://m.media-amazon.com/images/I/61fy+u9uqPL._SX679_.jpg",
              "price": 22000,
            },
            {
              "id": 27,
              "name": "OnePlus 10 Pro",
              "category": "Mobile",
              "image": "https://m.media-amazon.com/images/I/61mIUCd-37L._SL1500_.jpg",
              "price": 19500,
            
            },
            {
              "id": 28,
              "name": "OnePlus 10 R",
              "category": "Mobile",
              "image": "https://m.media-amazon.com/images/I/716uVx3Wr5L._AC_SS450_.jpg",
              "price": 35000,
            },
            {
              "id": 29,
              "name": "OnePlus Nord 2T",
              "category": "Mobile",
              "image": "https://m.media-amazon.com/images/I/617MPEZB5mL._SL1500_.jpg",
              "price": 16500,
            },
            {
              "id": 30,
              "name": "OnePlus 11R 5G ",
              "category": "Ipad",
              "image": "https://m.media-amazon.com/images/I/41g1pQr8xUL._SX300_SY300_QL70_FMwebp_.jpg",
              "price": 40999,
            },
           
              {
                  "id": 1,
                  "name": "iPhone 9",
                  "description": "An apple mobile which is nothing like apple",
                  "price": 549,
                  "discountPercentage": 12.96,
                  "rating": 4.69,
                  "stock": 94,
                  "brand": "Apple",
                  "category": "smartphones",
                  "thumbnail": "https://i.dummyjson.com/data/products/1/thumbnail.jpg",
                  "image": 
                      "https://i.dummyjson.com/data/products/1/1.jpg",
                    
              },
              {
                  "id": 2,
                  "name": "iPhone X",
                  "description": "SIM-Free, Model A19211 6.5-inch Super Retina HD display with OLED technology A12 Bionic chip with ...",
                  "price": 899,
                  "discountPercentage": 17.94,
                  "rating": 4.44,
                  "stock": 34,
                  "brand": "Apple",
                  "category": "smartphones",
                  "thumbnail": "https://i.dummyjson.com/data/products/2/thumbnail.jpg",
                  "image": 
                      "https://i.dummyjson.com/data/products/2/1.jpg",
                    
              },
              {
                  "id": 3,
                  "name": "Samsung Universe 9",
                  "description": "Samsung's new variant which goes beyond Galaxy to the Universe",
                  "price": 1249,
                  "discountPercentage": 15.46,
                  "rating": 4.09,
                  "stock": 36,
                  "brand": "Samsung",
                  "category": "smartphones",
                  "thumbnail": "https://i.dummyjson.com/data/products/3/thumbnail.jpg",
                  "image": 
                      "https://i.dummyjson.com/data/products/3/1.jpg"
                  
              },
              {
                  "id": 4,
                  "name": "OPPOF19",
                  "description": "OPPO F19 is officially announced on April 2021.",
                  "price": 280,
                  "discountPercentage": 17.91,
                  "rating": 4.3,
                  "stock": 123,
                  "brand": "OPPO",
                  "category": "smartphones",
                  "thumbnail": "https://i.dummyjson.com/data/products/4/thumbnail.jpg",
                  "image": 
                      "https://i.dummyjson.com/data/products/4/1.jpg",
                 
              },
              {
                  "id": 5,
                  "name": "Huawei P30",
                  "description": "Huawei’s re-badged P30 Pro New Edition was officially unveiled yesterday in Germany and now the device has made its way to the UK.",
                  "price": 499,
                  "discountPercentage": 10.58,
                  "rating": 4.09,
                  "stock": 32,
                  "brand": "Huawei",
                  "category": "smartphones",
                  "thumbnail": "https://i.dummyjson.com/data/products/5/thumbnail.jpg",
                  "image": 
                      "https://i.dummyjson.com/data/products/5/1.jpg",
                 
              },
              {
                  "id": 6,
                  "name": "MacBook Pro",
                  "description": "MacBook Pro 2021 with mini-LED display may launch between September, November",
                  "price": 1749,
                  "discountPercentage": 11.02,
                  "rating": 4.57,
                  "stock": 83,
                  "brand": "Apple",
                  "category": "laptops",
                  "thumbnail": "https://i.dummyjson.com/data/products/6/thumbnail.png",
                  "image": 
                      "https://i.dummyjson.com/data/products/6/1.png",
                   
              },
              {
                  "id": 7,
                  "name": "Samsung Galaxy Book",
                  "description": "Samsung Galaxy Book S (2020) Laptop With Intel Lakefield Chip, 8GB of RAM Launched",
                  "price": 1499,
                  "discountPercentage": 4.15,
                  "rating": 4.25,
                  "stock": 50,
                  "brand": "Samsung",
                  "category": "laptops",
                  "thumbnail": "https://i.dummyjson.com/data/products/7/thumbnail.jpg",
                  "image": 
                      "https://i.dummyjson.com/data/products/7/1.jpg",
                     
              },
              {
                  "id": 8,
                  "name": "Microsoft Surface Laptop 4",
                  "description": "Style and speed. Stand out on HD video calls backed by Studio Mics. Capture ideas on the vibrant touchscreen.",
                  "price": 1499,
                  "discountPercentage": 10.23,
                  "rating": 4.43,
                  "stock": 68,
                  "brand": "Microsoft Surface",
                  "category": "laptops",
                  "thumbnail": "https://i.dummyjson.com/data/products/8/thumbnail.jpg",
                  "image": 
                      "https://i.dummyjson.com/data/products/8/1.jpg",
                  
              },
              {
                  "id": 9,
                  "name": "Infinix INBOOK",
                  "description": "Infinix Inbook X1 Ci3 10th 8GB 256GB 14 Win10 Grey – 1 Year Warranty",
                  "price": 1099,
                  "discountPercentage": 11.83,
                  "rating": 4.54,
                  "stock": 96,
                  "brand": "Infinix",
                  "category": "laptops",
                  "thumbnail": "https://i.dummyjson.com/data/products/9/thumbnail.jpg",
                  "image": 
                      "https://i.dummyjson.com/data/products/9/1.jpg",
                   
              },
              {
                  "id": 10,
                  "name": "HP Pavilion 15-DK1056WM",
                  "description": "HP Pavilion 15-DK1056WM Gaming Laptop 10th Gen Core i5, 8GB, 256GB SSD, GTX 1650 4GB, Windows 10",
                  "price": 1099,
                  "discountPercentage": 6.18,
                  "rating": 4.43,
                  "stock": 89,
                  "brand": "HP Pavilion",
                  "category": "laptops",
                  "thumbnail": "https://i.dummyjson.com/data/products/10/thumbnail.jpeg",
                  "image": "https://i.dummyjson.com/data/products/10/1.jpg"        
              }               
    ])
}

module.exports.apiController = get